$schema: http://json-schema.org/draft-04/schema#
id: site
title: site
type: object
namespace: https://omix3.test.biocommons.org.au/
category: clinical
program: '*'
project: '*'
description: 'The site where the participant was assessed and/or where the biospecimen
  was collected/analysed.

  '
submittable: true
validators: null
systemProperties:
- id
- project_id
- state
- created_datetime
- updated_datetime
uniqueKeys:
- - id
- - project_id
  - submitter_id
required:
- submitter_id
- type
links:
- name: subjects
  backref: sites
  label: part_of
  target_type: subject
  multiplicity: one_to_one
  required: true
properties:
  $ref: _definitions.yaml#/ubiquitous_properties
  site_name:
    description: Name of the site
    enum:
    - Px4 Health Participant Assessment Centre
    - Px4 Health Multi-omics Platform
    - Australian Genome Research Facility
    - Murdoch Children's Research Institute
    - Other
  site_location:
    type: string
    description: Geographical location of the site
  site_protocol_version:
    type: string
    description: Version of the process protocol used at the site
  site_purpose:
    description: Purpose of the site
    enum:
    - Participant assessment
    - Biospecimen collection
    - Biospecimen analysis
  subjects:
    $ref: _definitions.yaml#/to_one
additionalProperties: false
