$schema: http://json-schema.org/draft-04/schema#
id: environmental_measurements
title: environmental_measurements
type: object
namespace: https://omix3.test.biocommons.org.au/
category: clinical
program: '*'
project: '*'
description: 'Environmental exposure measurements taken for the participant at baseline.

  '
submittable: true
validators: null
systemProperties:
- id
- project_id
- state
- created_datetime
- updated_datetime
uniqueKeys:
- - id
- - project_id
  - submitter_id
required:
- submitter_id
- type
links:
- name: sites
  backref: environmental_measurementss
  label: part_of
  target_type: site
  multiplicity: one_to_one
  required: false
properties:
  $ref: _definitions.yaml#/ubiquitous_properties
  greenspace_proximity:
    description: Walking time from home to the nearest green or natural space.
    enum:
    - Fewer than 5 minutes
    - 5-9 minutes
    - 10-19 minutes
    - 20-30 minutes
    - More than 30 minutes
    - No green space/too far to walk
  household_size:
    type: integer
    description: Total number of people living in the household including the participant.
  sites:
    $ref: _definitions.yaml#/to_one
additionalProperties: false
